// Auto-generated Rust FFI bindings for NFMWorld.Library, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// Generated by NFMWorld.RustBindGen
// Do not edit this file directly

unsafe extern "system" {
  pub fn nfmw_validate_radpack(args: *const ValidateRadpackArgs) -> ValidateRadpackResult;
}

unsafe extern "system" {
  /// Gets information for a time trial.
  pub fn nfmw_get_tt_info(args: *const GetTTInfoArgs) -> GetTTInfoResult;
}

unsafe extern "system" {
  /// Loads the backend. Call before calling any other functions.
  pub fn nfmw_load() -> LoadResult;
}

unsafe extern "system" {
  /// Simulates a time trial to completion with a limit of 100M ticks. Returns the number of elapsed ticks, or -1 on
  /// timeout.
  pub fn nfmw_simulate_tt(args: *const SimulateTimeTrialArgs) -> SimulateTimeTrialResult;
}

#[repr(C)]
pub struct ValidateRadpackResult {
    pub rad_type: RadpackType,
    /// Whether an error occurred during ValidateRadpack
    pub has_error: bool,
    /// Error information if HasError is true
    pub exception: NativeException,
}

#[repr(C)]
pub struct ValidateRadpackArgs {
    /// Pointer to radpack data
    pub radpack_data: *const u8,
    /// Length of radpack data in bytes
    pub radpack_data_length: i32,
}

#[repr(C)]
pub struct GetTTInfoResult {
    /// Number of checkpoints in the time trial
    pub checkpoint_count: i32,
    /// Number of ticks in the time trial
    pub tick_count: i32,
    /// Version of the replay
    pub replay_version: i32,
    /// Version of the backend
    pub backend_version: i32,
    /// Whether an error occurred during GetTTInfo
    pub has_error: bool,
    /// Error information if HasError is true
    pub exception: NativeException,
}

#[repr(C)]
pub struct GetTTInfoArgs {
    /// Pointer to time trial data
    pub time_trial_data: *const u8,
    /// Length of time trial data in bytes
    pub time_trial_data_length: i32,
}

#[repr(C)]
pub struct LoadResult {
    /// Whether an error occurred during LoadUnmanaged
    pub has_error: bool,
    /// Error information if HasError is true
    pub exception: NativeException,
}

#[repr(C)]
pub struct SimulateTimeTrialResult {
    /// The result code: number of ticks elapsed, or -1 on timeout or error
    pub elapsed_ticks: i32,
    /// Number of input ticks in the replay
    pub expected_ticks: i32,
    /// Whether an error occurred
    pub has_error: bool,
    /// Error information
    pub exception: NativeException,
}

#[repr(C)]
pub struct SimulateTimeTrialArgs {
    /// Pointer to UTF-8 encoded stage name, null-terminated
    pub stage_name: *const u8,
    /// Pointer to array of CarInfoUnmanaged
    pub cars: *const CarInfoUnmanaged,
    /// Number of cars
    pub car_count: i32,
    /// Pointer to time trial data
    pub time_trial_data: *const u8,
    /// Length of time trial data
    pub time_trial_data_length: i32,
}

#[repr(C)]
pub struct RadpackType {
    pub value__: u8,
}

#[repr(C)]
pub struct NativeException {
    /// Type name of the exception (UTF-8 bytes, null-terminated)
    pub type_name: [u8; 1024],
    /// Message of the exception (UTF-8 bytes, null-terminated)
    pub message: [u8; 1024],
    /// Stack trace of the exception (UTF-8 bytes, null-terminated)
    pub stack_trace: [u8; 16384],
}

#[repr(C)]
pub struct CarInfoUnmanaged {
    /// Pointer to UTF-8 encoded car name, null-terminated
    pub car_name: *const u8,
}


