// Auto-generated Rust FFI bindings for BackendGameSparker
// Generated by NFMWorld.RustBindGen
// Do not edit this file directly

unsafe extern "system" {
  pub fn nfmw_get_tt_info(args: *const GetTTInfoArgs) -> GetTTInfoResult;
}

unsafe extern "system" {
  pub fn nfmw_simulate_tt(args: *const SimulateTimeTrialArgs) -> SimulateTimeTrialResult;
}

#[repr(C)]
pub struct GetTTInfoResult {
    pub checkpoint_count: i32,
    pub tick_count: i32,
    pub replay_version: i32,
    pub backend_version: i32,
    pub has_error: bool,
    pub exception: NativeException,
}

#[repr(C)]
pub struct GetTTInfoArgs {
    pub time_trial_data: *const u8,
    pub time_trial_data_length: i32,
}

#[repr(C)]
pub struct SimulateTimeTrialResult {
    pub elapsed_ticks: i32,
    pub expected_ticks: i32,
    pub has_error: bool,
    pub exception: NativeException,
}

#[repr(C)]
pub struct SimulateTimeTrialArgs {
    pub stage_name: *const u8,
    pub cars: *const CarInfoUnmanaged,
    pub car_count: i32,
    pub time_trial_data: *const u8,
    pub time_trial_data_length: i32,
}

#[repr(C)]
pub struct NativeException {
    pub type_name: [u8; 1024],
    pub message: [u8; 1024],
    pub stack_trace: [u8; 16384],
}

#[repr(C)]
pub struct CarInfoUnmanaged {
    pub car_name: *const u8,
}


